### ISSUE TITLE
Min SDK can be 14.

### ISSUE THREAD

**Issue by SoftNirav** [MFlisar/GDPRDialog#15]
Please keep the minimum SDK to be 14.
Admob supports minSdkVersion >= 14.
Keeping it 14 will enable all developers (like me) to use GDPR Dialog.

**Comment by MFlisar** [comment]
Will change that.

This is the only line that may not work though (not important as long as you are in the first activity though).

https://github.com/MFlisar/GDPRDialog/blob/e7a8efa1309740b318099d1089a2c4256501df1e/library/src/main/java/com/michaelflisar/gdprdialog/GDPRDialog.java#L147

I somewhere have read it works on API 15, but not on API 14 or below... Still, this actually should be no problem because you normally show the dialog in your first activity and then everything is fine

**Comment by orium-dev** [comment]
There is no need for that because there are no such real devices with 14 sdk version in the world
